// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clip: typeof import('./src/components/Timeline/Clip.vue')['default']
    ClipMini: typeof import('./src/components/Timeline/ClipMini.vue')['default']
    DraggingClips: typeof import('./src/components/Timeline/DraggingClips.vue')['default']
    Medias: typeof import('./src/components/Editor/Medias.vue')['default']
    Monitor: typeof import('./src/components/Editor/Monitor.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Ruler: typeof import('./src/components/Timeline/Ruler.vue')['default']
    SeekLine: typeof import('./src/components/Timeline/SeekLine.vue')['default']
    Timeline: typeof import('./src/components/Timeline/Timeline.vue')['default']
    TitleBar: typeof import('./src/components/Editor/TitleBar.vue')['default']
    ToolsBar: typeof import('./src/components/Timeline/ToolsBar.vue')['default']
    Track: typeof import('./src/components/Timeline/Track.vue')['default']
    TrackContainer: typeof import('./src/components/Timeline/TrackContainer.vue')['default']
    TrackControls: typeof import('./src/components/Timeline/TrackControls.vue')['default']
  }
}

export {}
